CREATE TABLE bronze.races (
	raceId INTEGER,
	year INTEGER,
	round INTEGER,
	circuitId INTEGER,
	name TEXT,
	date TEXT,
	time TEXT,
	url TEXT,
	fp1_date TEXT,
	fp1_time TEXT,
	fp2_date TEXT,
	fp2_time TEXT,
	fp3_date TEXT,
	fp3_time TEXT,
	quali_date TEXT,
	quali_time TEXT,
	sprint_date TEXT,
	sprint_time TEXT
)