# This is a basic workflow to help you get started with Actions

name: flyway-migration

# Controls when the workflow will run
on:

  workflow_dispatch:
    inputs:
      flyway-clean:
        type: boolean
        required: true
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ################################################# Job called "test"
  migration:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out source code
        uses: actions/checkout@v3

      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://dip-analytics-engineer-training-postgresql.postgres.database.azure.com:5432/ae_training
          user: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASSWORD }}
          locations: filesystem:flyway/
        env:
#          FLYWAY_USER: $FLYWAY_USER
#          FLYWAY_PASSWORD: $FLYWAY_PASSWORD
          FLYWAY_DEFAULT_SCHEMA: flyway
          FLYWAY_CREATE_SCHEMA: true
          FLYWAY_SCHEMAS: bronze,silver,gold,flyway
#          FLYWAY_URL: jdbc:postgresql://dip-analytics-engineer-training-postgresql.postgres.database.azure.com:5432/ae_training
#          FLYWAY_LOCATIONS: filesystem:/flyway/sql/
          FLYWAY_CONNECT_RETRIES: 3
          FLYWAY_CLEAN_DISABLED: false
          FLYWAY_CLEAN: true
          FLYWAY_MIGRATE: true
